### ISSUE TITLE
在D1上烧写完zCore，启动后显示异常的问题

### ISSUE THREAD

**Issue by shzhxh** [YdrMaster/nezha-boot-util#1]
#### 现象
字符都挤到了最右侧，如图所示：
![nezha-flash](https://user-images.githubusercontent.com/17696265/180142522-9b6310a6-ddc9-4ff8-8668-636b92d710e6.png)

#### 操作过程
zCore镜像的制作(cmmit id : 757c63d96dba0f1e02a5ae2e6d76bc59e592d2da)：
```
cargo bin --arch riscv64 --features "linux board-d1 link-user-img" --output z.bin
```
烧写操作：
```
cargo make --spl --see --dt nezha.dts
cargo flash --spl
cargo flash --see --reset
cargo flash --dt nezha.dts
cargo flash --kernel z.bin
```

**Comment by YdrMaster** [comment]
[已改](https://github.com/YdrMaster/nezha-boot-util/commit/76ae2c07216568b95dfc503fbc90be48e5c8a8d6)。

烧写直接 `cargo --spl --see --dt nezha.dts --kernel z.bin` 就行了，分开写导致反复刷 flash，浪费寿命。
